added -h|--help /general argument parsing

diff --git a/bin/setenv b/bin/setenv
--- a/bin/setenv
+++ b/bin/setenv
@@ -32,7 +32,7 @@
 ##
 ## \par Usage
 ## Only the invocation of this script matters; all arguments are
-## ignored. Invoke the script as follows:
+## ignored save -h|--help. Invoke the script as follows:
 ##
 ## \code
 ## source ./setenv
@@ -40,5 +40,43 @@
 #
 ## \addtogroup environment
 
+# Execute getopt
+ARGS=$(getopt -o h -l "help" -n "$0" -- "$@");
+
+# Fail on bad arguments
+if [ $? -ne 0 ]; then
+    exit 1
+fi
+
+eval set -- "${ARGS}";
+
+## @var HELP
+## @brief Contains script invocation information
+## @details Contains script invocation information and abstract.
+## @ingroup environment
+declare HELP
+HELP=$(cat <<'EOF'
+source $0 : Set up the development environment for ee445m.
+
+Usage : source $0 [-h]
+
+  -h : print this help menu
+
+EOF
+)
+
+# Obey command line arguments
+while true; do
+    case "$1" in
+	-h|--help)
+	    echo -e "${HELP}"
+	    ;;
+	--)
+	    break ;;
+    esac
+    shift
+done
+
 # Add this directory to the working PATH
+# TODO: change to modpath
 export PATH="$(pwd):$PATH"
